[package]
name = "fade"
version = "1.0.0"
authors = ["Oupson <oupson1er@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
gif = "0.10.3"